local wk = require("which-key")

wk.setup({
	preset = "modern",
	delay = 300,
	plugins = {
		spelling = { enabled = true },
	},
})

wk.add({
	{ "<M-d>", desc = "Visual multi: próxima ocorrência" },
	{ "<M-j>", desc = "Move linha/seleção para baixo" },
	{ "<M-k>", desc = "Move linha/seleção para cima" },
	{ "<M-v>", desc = "Colar clipboard (insert)", mode = "i" },
	{ "<leader>b", group = "Buffer" },
	{ "<leader>bV", desc = "Buffer alternado → vsplit" },
	{ "<leader>bS", desc = "Buffer alternado → split horizontal" },
	{ "<leader>a", desc = "Toggle outline (Aerial)" },
	{ "<leader>.", desc = "Scratch buffer" },
	{ "<leader>S", desc = "Select scratch buffer" },
	{ "<leader>z", desc = "Zen mode" },
	{ "<leader>d", group = "Debug" },
	{ "<leader>cR", desc = "Rename file (LSP)" },
	{ "<leader>e", desc = "Explorer toggle" },
	{ "<leader>E", desc = "Explorer focus" },
	{ "<leader>f", group = "Finder" },
	{ "<leader>fm", desc = "Telescope media (image preview)" },
	{ "<leader>fs", desc = "Snacks smart find" },
	{ "<leader>g", group = "Git/Diagnostics" },
	{ "<leader>l", group = "Lint" },
	{ "<leader>O", group = "Obsidian" },
	{ "<leader>Oq", desc = "Quick switch note" },
	{ "<leader>Os", desc = "Search vault" },
	{ "<leader>On", desc = "New note" },
	{ "<leader>Ot", desc = "Daily note" },
	{ "<leader>n", group = "Notifications" },
	{ "<leader>nh", desc = "Notification history" },
	{ "<leader>o", desc = "Reveal in explorer" },
	{ "<leader>r", group = "Rust/Crates" },
	{ "<leader>s", group = "Search" },
	{ "<leader>t", group = "Terminal/Test" },
	{ "<leader>u", group = "UI / toggles" },
	{ "<leader>un", desc = "Dismiss notifications" },
	{ "<leader>x", group = "Diagnostics Panel" },
	{ "<leader>yy", desc = "Copiar linha pro clipboard" },
	{ "<leader>y", desc = "Copiar seleção pro clipboard", mode = "v" },
	{ "<leader>p", desc = "Colar clipboard depois do cursor", mode = "n" },
	{ "<leader>p", desc = "Substituir seleção pelo clipboard", mode = "v" },
	{ "<leader>P", desc = "Colar clipboard antes do cursor", mode = "n" },
})
